// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzaCleanApp.Infrastructure.Database;

#nullable disable

namespace PizzaCleanApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260116222409_Insert_Identity_Users")]
    partial class Insert_Identity_Users
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PizzaCleanApp.Core.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PizzaCleanApp.Core.Models.Crust", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Crusts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Calories = 90,
                            CreateDate = new DateTime(2025, 12, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LastUpdated = new DateTime(2025, 12, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Thin Crust"
                        },
                        new
                        {
                            Id = 2L,
                            Calories = 120,
                            CreateDate = new DateTime(2025, 12, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LastUpdated = new DateTime(2025, 12, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Original Crust"
                        },
                        new
                        {
                            Id = 3L,
                            Calories = 150,
                            CreateDate = new DateTime(2025, 12, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LastUpdated = new DateTime(2025, 12, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Thick Crust"
                        },
                        new
                        {
                            Id = 4L,
                            Calories = 200,
                            CreateDate = new DateTime(2025, 12, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LastUpdated = new DateTime(2025, 12, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Stuffed Crust"
                        });
                });

            modelBuilder.Entity("PizzaCleanApp.Core.Models.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("PizzaCleanApp.Core.Models.OrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CrustId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<long>("PizzaId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<long>("SizeId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("SubtotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CrustId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PizzaId");

                    b.HasIndex("SizeId");

                    b.ToTable("OrderItems", (string)null);
                });

            modelBuilder.Entity("PizzaCleanApp.Core.Models.OrderItemToppings", b =>
                {
                    b.Property<long>("OrderItemId")
                        .HasColumnType("bigint");

                    b.Property<long>("ToppingId")
                        .HasColumnType("bigint");

                    b.HasKey("OrderItemId", "ToppingId");

                    b.HasIndex("ToppingId");

                    b.HasIndex("OrderItemId", "ToppingId")
                        .IsUnique();

                    b.ToTable("OrderItemToppings", (string)null);
                });

            modelBuilder.Entity("PizzaCleanApp.Core.Models.Pizza", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Pizzas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BasePrice = 8.00m,
                            CreateDate = new DateTime(2025, 12, 31, 2, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Classic pizza with pepperoni slices.",
                            IsActive = true,
                            LastUpdated = new DateTime(2025, 12, 31, 2, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Pepperoni"
                        },
                        new
                        {
                            Id = 2L,
                            BasePrice = 12.50m,
                            CreateDate = new DateTime(2025, 12, 31, 2, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Deluxe pizza with a variety of toppings.",
                            IsActive = true,
                            LastUpdated = new DateTime(2025, 12, 31, 2, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Supreme"
                        });
                });

            modelBuilder.Entity("PizzaCleanApp.Core.Models.PizzaTopping", b =>
                {
                    b.Property<long>("PizzaId")
                        .HasColumnType("bigint");

                    b.Property<long>("ToppingId")
                        .HasColumnType("bigint");

                    b.HasKey("PizzaId", "ToppingId");

                    b.HasIndex("PizzaId");

                    b.HasIndex("ToppingId");

                    b.ToTable("PizzaToppings", (string)null);

                    b.HasData(
                        new
                        {
                            PizzaId = 1L,
                            ToppingId = 1L
                        },
                        new
                        {
                            PizzaId = 2L,
                            ToppingId = 1L
                        },
                        new
                        {
                            PizzaId = 2L,
                            ToppingId = 2L
                        },
                        new
                        {
                            PizzaId = 2L,
                            ToppingId = 4L
                        },
                        new
                        {
                            PizzaId = 2L,
                            ToppingId = 5L
                        },
                        new
                        {
                            PizzaId = 2L,
                            ToppingId = 6L
                        });
                });

            modelBuilder.Entity("PizzaCleanApp.Core.Models.Size", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Sizes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Calories = 186,
                            CreateDate = new DateTime(2025, 12, 21, 2, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdated = new DateTime(2025, 12, 21, 2, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Small",
                            Price = 8.00m
                        },
                        new
                        {
                            Id = 2L,
                            Calories = 220,
                            CreateDate = new DateTime(2025, 12, 21, 2, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdated = new DateTime(2025, 12, 21, 2, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Medium",
                            Price = 10.00m
                        },
                        new
                        {
                            Id = 3L,
                            Calories = 286,
                            CreateDate = new DateTime(2025, 12, 21, 2, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdated = new DateTime(2025, 12, 21, 2, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Large",
                            Price = 12.00m
                        });
                });

            modelBuilder.Entity("PizzaCleanApp.Core.Models.Topping", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<string>("CategoryType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Toppings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Calories = 54,
                            CategoryType = "Meat",
                            CreateDate = new DateTime(2025, 12, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LastUpdated = new DateTime(2025, 12, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Pepperoni",
                            Price = 1.50m
                        },
                        new
                        {
                            Id = 2L,
                            Calories = 61,
                            CategoryType = "Meat",
                            CreateDate = new DateTime(2025, 12, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LastUpdated = new DateTime(2025, 12, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Meatballs",
                            Price = 2.00m
                        },
                        new
                        {
                            Id = 3L,
                            Calories = 25,
                            CategoryType = "Meat",
                            CreateDate = new DateTime(2025, 12, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LastUpdated = new DateTime(2025, 12, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Steak",
                            Price = 1.75m
                        },
                        new
                        {
                            Id = 4L,
                            Calories = 3,
                            CategoryType = "Vegetable",
                            CreateDate = new DateTime(2025, 12, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LastUpdated = new DateTime(2025, 12, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Mushrooms",
                            Price = 1.00m
                        },
                        new
                        {
                            Id = 5L,
                            Calories = 5,
                            CategoryType = "Vegetable",
                            CreateDate = new DateTime(2025, 12, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LastUpdated = new DateTime(2025, 12, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Onions",
                            Price = 0.75m
                        },
                        new
                        {
                            Id = 6L,
                            Calories = 4,
                            CategoryType = "Vegetable",
                            CreateDate = new DateTime(2025, 12, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LastUpdated = new DateTime(2025, 12, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Green Peppers",
                            Price = 0.80m
                        },
                        new
                        {
                            Id = 7L,
                            Calories = 10,
                            CategoryType = "Vegetable",
                            CreateDate = new DateTime(2025, 12, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastUpdated = new DateTime(2025, 12, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Pineapple",
                            Price = 1.20m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PizzaCleanApp.Core.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PizzaCleanApp.Core.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzaCleanApp.Core.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PizzaCleanApp.Core.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PizzaCleanApp.Core.Models.OrderItem", b =>
                {
                    b.HasOne("PizzaCleanApp.Core.Models.Crust", "Crust")
                        .WithMany()
                        .HasForeignKey("CrustId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PizzaCleanApp.Core.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzaCleanApp.Core.Models.Pizza", "Pizza")
                        .WithMany()
                        .HasForeignKey("PizzaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PizzaCleanApp.Core.Models.Size", "Size")
                        .WithMany()
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Crust");

                    b.Navigation("Order");

                    b.Navigation("Pizza");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("PizzaCleanApp.Core.Models.OrderItemToppings", b =>
                {
                    b.HasOne("PizzaCleanApp.Core.Models.OrderItem", "OrderItem")
                        .WithMany("OrderToppings")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzaCleanApp.Core.Models.Topping", "Topping")
                        .WithMany()
                        .HasForeignKey("ToppingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrderItem");

                    b.Navigation("Topping");
                });

            modelBuilder.Entity("PizzaCleanApp.Core.Models.PizzaTopping", b =>
                {
                    b.HasOne("PizzaCleanApp.Core.Models.Pizza", "Pizza")
                        .WithMany("PizzaToppings")
                        .HasForeignKey("PizzaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzaCleanApp.Core.Models.Topping", "Topping")
                        .WithMany()
                        .HasForeignKey("ToppingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pizza");

                    b.Navigation("Topping");
                });

            modelBuilder.Entity("PizzaCleanApp.Core.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("PizzaCleanApp.Core.Models.OrderItem", b =>
                {
                    b.Navigation("OrderToppings");
                });

            modelBuilder.Entity("PizzaCleanApp.Core.Models.Pizza", b =>
                {
                    b.Navigation("PizzaToppings");
                });
#pragma warning restore 612, 618
        }
    }
}
