// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzaCleanApp.Infrastructure.Database;

#nullable disable

namespace PizzaCleanApp.Infrastructure.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.1")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("PizzaCleanApp.Core.Models.Crust", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                b.Property<int>("Calories")
                    .HasColumnType("int");

                b.Property<DateTime>("CreateDate")
                    .HasColumnType("datetime2");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<DateTime>("LastUpdated")
                    .HasColumnType("datetime2");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.HasKey("Id");

                b.ToTable("Crusts", (string)null);

                b.HasData(
                    new
                    {
                        Id = 1L,
                        Calories = 90,
                        CreateDate = new DateTime(2025, 12, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                        IsActive = true,
                        LastUpdated = new DateTime(2025, 12, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                        Name = "Thin Crust"
                    },
                    new
                    {
                        Id = 2L,
                        Calories = 120,
                        CreateDate = new DateTime(2025, 12, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                        IsActive = true,
                        LastUpdated = new DateTime(2025, 12, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                        Name = "Original Crust"
                    },
                    new
                    {
                        Id = 3L,
                        Calories = 150,
                        CreateDate = new DateTime(2025, 12, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                        IsActive = true,
                        LastUpdated = new DateTime(2025, 12, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                        Name = "Thick Crust"
                    },
                    new
                    {
                        Id = 4L,
                        Calories = 200,
                        CreateDate = new DateTime(2025, 12, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                        IsActive = true,
                        LastUpdated = new DateTime(2025, 12, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                        Name = "Stuffed Crust"
                    });
            });

        modelBuilder.Entity("PizzaCleanApp.Core.Models.Order", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                b.Property<DateTime>("CreateDate")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("LastUpdated")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("OrderDate")
                    .HasColumnType("datetime2");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("Orders", (string)null);
            });

        modelBuilder.Entity("PizzaCleanApp.Core.Models.OrderItem", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                b.Property<DateTime>("CreateDate")
                    .HasColumnType("datetime2");

                b.Property<long>("CrustId")
                    .HasColumnType("bigint");

                b.Property<DateTime>("LastUpdated")
                    .HasColumnType("datetime2");

                b.Property<long>("OrderId")
                    .HasColumnType("bigint");

                b.Property<long>("PizzaId")
                    .HasColumnType("bigint");

                b.Property<int>("Quantity")
                    .HasColumnType("int");

                b.Property<long>("SizeId")
                    .HasColumnType("bigint");

                b.Property<decimal>("SubtotalPrice")
                    .HasPrecision(18, 2)
                    .HasColumnType("decimal(18,2)");

                b.HasKey("Id");

                b.HasIndex("CrustId");

                b.HasIndex("OrderId");

                b.HasIndex("PizzaId");

                b.HasIndex("SizeId");

                b.ToTable("OrderItems", (string)null);
            });

        modelBuilder.Entity("PizzaCleanApp.Core.Models.OrderItemToppings", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                b.Property<long>("OrderItemId")
                    .HasColumnType("bigint");

                b.Property<long>("ToppingId")
                    .HasColumnType("bigint");

                b.HasKey("Id");

                b.HasIndex("ToppingId");

                b.HasIndex("OrderItemId", "ToppingId")
                    .IsUnique();

                b.ToTable("OrderItemToppings", (string)null);
            });

        modelBuilder.Entity("PizzaCleanApp.Core.Models.Pizza", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                b.Property<decimal>("BasePrice")
                    .HasPrecision(18, 2)
                    .HasColumnType("decimal(18,2)");

                b.Property<DateTime>("CreateDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<DateTime>("LastUpdated")
                    .HasColumnType("datetime2");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.HasKey("Id");

                b.ToTable("Pizzas", (string)null);
            });

        modelBuilder.Entity("PizzaCleanApp.Core.Models.PizzaTopping", b =>
            {
                b.Property<long>("PizzaId")
                    .HasColumnType("bigint");

                b.Property<long>("ToppingId")
                    .HasColumnType("bigint");

                b.HasKey("PizzaId", "ToppingId");

                b.HasIndex("PizzaId");

                b.HasIndex("ToppingId");

                b.ToTable("PizzaToppings", (string)null);
            });

        modelBuilder.Entity("PizzaCleanApp.Core.Models.Size", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                b.Property<DateTime>("CreateDate")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("LastUpdated")
                    .HasColumnType("datetime2");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<decimal>("Price")
                    .HasPrecision(18, 2)
                    .HasColumnType("decimal(18,2)");

                b.HasKey("Id");

                b.ToTable("Sizes", (string)null);
            });

        modelBuilder.Entity("PizzaCleanApp.Core.Models.Topping", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                b.Property<int>("Calories")
                    .HasColumnType("int");

                b.Property<int>("CategoryType")
                    .HasColumnType("int");

                b.Property<DateTime>("CreateDate")
                    .HasColumnType("datetime2");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<DateTime>("LastUpdated")
                    .HasColumnType("datetime2");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<decimal>("Price")
                    .HasPrecision(18, 2)
                    .HasColumnType("decimal(18,2)");

                b.HasKey("Id");

                b.ToTable("Toppings", (string)null);

                b.HasData(
                    new
                    {
                        Id = 1L,
                        Calories = 54,
                        CategoryType = 1,
                        CreateDate = new DateTime(2025, 12, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                        IsActive = true,
                        LastUpdated = new DateTime(2025, 12, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                        Name = "Pepperoni",
                        Price = 1.50m
                    },
                    new
                    {
                        Id = 2L,
                        Calories = 61,
                        CategoryType = 1,
                        CreateDate = new DateTime(2025, 12, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                        IsActive = true,
                        LastUpdated = new DateTime(2025, 12, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                        Name = "Meatballs",
                        Price = 2.00m
                    },
                    new
                    {
                        Id = 3L,
                        Calories = 25,
                        CategoryType = 1,
                        CreateDate = new DateTime(2025, 12, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                        IsActive = true,
                        LastUpdated = new DateTime(2025, 12, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                        Name = "Steak",
                        Price = 1.75m
                    },
                    new
                    {
                        Id = 4L,
                        Calories = 3,
                        CategoryType = 0,
                        CreateDate = new DateTime(2025, 12, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                        IsActive = true,
                        LastUpdated = new DateTime(2025, 12, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                        Name = "Mushrooms",
                        Price = 1.00m
                    },
                    new
                    {
                        Id = 5L,
                        Calories = 5,
                        CategoryType = 0,
                        CreateDate = new DateTime(2025, 12, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                        IsActive = true,
                        LastUpdated = new DateTime(2025, 12, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                        Name = "Onions",
                        Price = 0.75m
                    },
                    new
                    {
                        Id = 6L,
                        Calories = 4,
                        CategoryType = 0,
                        CreateDate = new DateTime(2025, 12, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                        IsActive = true,
                        LastUpdated = new DateTime(2025, 12, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                        Name = "Green Peppers",
                        Price = 0.80m
                    });
            });

        modelBuilder.Entity("PizzaCleanApp.Core.Models.OrderItem", b =>
            {
                b.HasOne("PizzaCleanApp.Core.Models.Crust", "Crust")
                    .WithMany()
                    .HasForeignKey("CrustId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("PizzaCleanApp.Core.Models.Order", "Order")
                    .WithMany("Items")
                    .HasForeignKey("OrderId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("PizzaCleanApp.Core.Models.Pizza", "Pizza")
                    .WithMany()
                    .HasForeignKey("PizzaId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("PizzaCleanApp.Core.Models.Size", "Size")
                    .WithMany()
                    .HasForeignKey("SizeId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Crust");

                b.Navigation("Order");

                b.Navigation("Pizza");

                b.Navigation("Size");
            });

        modelBuilder.Entity("PizzaCleanApp.Core.Models.OrderItemToppings", b =>
            {
                b.HasOne("PizzaCleanApp.Core.Models.OrderItem", "OrderItem")
                    .WithMany("Toppings")
                    .HasForeignKey("OrderItemId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("PizzaCleanApp.Core.Models.Topping", "Topping")
                    .WithMany()
                    .HasForeignKey("ToppingId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("OrderItem");

                b.Navigation("Topping");
            });

        modelBuilder.Entity("PizzaCleanApp.Core.Models.PizzaTopping", b =>
            {
                b.HasOne("PizzaCleanApp.Core.Models.Pizza", "Pizza")
                    .WithMany("PizzaToppings")
                    .HasForeignKey("PizzaId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("PizzaCleanApp.Core.Models.Topping", "Topping")
                    .WithMany()
                    .HasForeignKey("ToppingId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Pizza");

                b.Navigation("Topping");
            });

        modelBuilder.Entity("PizzaCleanApp.Core.Models.Order", b =>
            {
                b.Navigation("Items");
            });

        modelBuilder.Entity("PizzaCleanApp.Core.Models.OrderItem", b =>
            {
                b.Navigation("Toppings");
            });

        modelBuilder.Entity("PizzaCleanApp.Core.Models.Pizza", b =>
            {
                b.Navigation("PizzaToppings");
            });
#pragma warning restore 612, 618
    }
}
